services:
  backend:
    build:
      context: ./backend
    ports:
      - "8001:8001"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - ewa-net
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - ewa-net
networks:
  ewa-net:
    driver: bridge
