services:
  backend:
    build:
      context: ./backend
    ports:
      - "8001:8001"
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - ewa-net
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE: "http://localhost:8001"
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - ewa-net
networks:
  ewa-net:
    driver: bridge
