name: Build and Push Docker Images to ACR

on:
  push:
    branches:
      - main  # Set to your default branch if different

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: sapservicesuk-g8b0edb8fthrbpgj.azurecr.io
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}


      - name: Build and Push Backend
        run: |
          docker build -t $REGISTRY/ewa-backend:latest ./backend
          docker push $REGISTRY/ewa-backend:latest

      - name: Build and Push Frontend
        run: |
          docker build -t $REGISTRY/ewa-frontend:latest ./frontend
          docker push $REGISTRY/ewa-frontend:latest
