name: Build and Push Docker Images to ACR

on:
  push:
    branches:
      - main  # Set to your default branch if different
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: sapservicesuk-g8b0edb8fthrbpgj.azurecr.io
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build and push backend with cache
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/ewa-backend:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/ewa-backend:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/ewa-backend:buildcache,mode=max

      - name: Build and push frontend with cache
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ env.REGISTRY }}/ewa-frontend:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/ewa-frontend:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/ewa-frontend:buildcache,mode=max
